import './globals.css';

import type {Metadata, Viewport} from 'next';
import localFont from 'next/font/local';
import {Sidebar} from '@/app/communication/components/Sidebar';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Infinivista',
    description: 'Generated by create next app',
};

export const viewport: Viewport = {
    initialScale: 1,
    width: 'device-width',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div className='bg-gray-100'>
                    <div className='container'>
                        <div className='relative flex min-h-screen bg-white'>
                            <aside className='w-[250px]'>
                                <Sidebar />
                            </aside>
                            <main className='w-[calc(100%-250px)] bg-white'>{children}</main>
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
