import './globals.css';

import type {Metadata, Viewport} from 'next';
import localFont from 'next/font/local';

import {ProgressBar} from '@/components/commons';
import {AxiosInterceptor} from '@/context';

const geistSans = localFont({
    src: './_fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './_fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Infinivista',
    description: 'Generated by create next app',
};

export const viewport: Viewport = {
    initialScale: 1,
    width: 'device-width',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning={true}>
                <div className='relative min-h-screen bg-white'>
                    <ProgressBar />
                    <AxiosInterceptor>{children}</AxiosInterceptor>
                </div>
            </body>
        </html>
    );
}
